spring.h2.console.enabled: true
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: manjulamanjula3150@gmail.com
  password: yxrr auju ljvz hsib
  properties.mail.smtp:
    auth: true
    starttls.enable: true